# https://jekyllrb.com/docs/configuration/default/
# Where things are

collections_dir     : ./collections
collections:
  blogs:
    output          : true

remote_theme: ankitsultana/researcher@gem
title: Hirotake Ito Profile
url: "https://HirotakeIto.github.io"
# baseurl: "HirotakeIto.github.io" # localでサーバーを立ち上げる時はコメントアウト.https://github.com/jekyll/jekyll/issues/1432
baseurl: # これならどっちでも平気

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "."
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
